// <auto-generated />
using System;
using LedgerLoop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LedgerLoop.Api.Data.Migrations
{
    [DbContext(typeof(LedgerLoopDbContext))]
    [Migration("20260918095510_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LedgerLoop.Api.Domain.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorRole")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_role");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("LedgerLoop.Api.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tax_id");

                    b.Property<string>("TaxOverride")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tax_override");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("LedgerLoop.Api.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("DocumentKind")
                        .HasColumnType("integer")
                        .HasColumnName("document_kind");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<decimal>("InvoiceDiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("invoice_discount_percent");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("invoice_number");

                    b.Property<decimal?>("ManualTaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("manual_tax_amount");

                    b.Property<string>("ManualTaxReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("manual_tax_reason");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OriginalInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_invoice_id");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<decimal>("PostingAdjustment")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("posting_adjustment");

                    b.Property<int>("PriceMode")
                        .HasColumnType("integer")
                        .HasColumnName("price_mode");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxTreatment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tax_treatment");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("LedgerLoop.Api.Domain.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("LineDiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("line_discount_percent");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rate_percent");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TreatmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("treatment_code");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "LineNumber")
                        .IsUnique();

                    b.ToTable("invoice_lines", (string)null);
                });

            modelBuilder.Entity("LedgerLoop.Api.Domain.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<int>("RateKind")
                        .HasColumnType("integer")
                        .HasColumnName("rate_kind");

                    b.Property<decimal>("RatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rate_percent");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "RateKind", "EffectiveFrom");

                    b.ToTable("tax_rates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "FR",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 0,
                            RatePercent = 20.0m
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "FR",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 1,
                            RatePercent = 10.0m
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "FR",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 2,
                            RatePercent = 2.1m
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "DE",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 0,
                            RatePercent = 19.0m
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "DE",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 1,
                            RatePercent = 7.0m
                        },
                        new
                        {
                            Id = 6,
                            CountryCode = "DE",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 2,
                            RatePercent = 5.0m
                        },
                        new
                        {
                            Id = 7,
                            CountryCode = "ES",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 0,
                            RatePercent = 21.0m
                        },
                        new
                        {
                            Id = 8,
                            CountryCode = "ES",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 1,
                            RatePercent = 10.0m
                        },
                        new
                        {
                            Id = 9,
                            CountryCode = "ES",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 2,
                            RatePercent = 4.0m
                        },
                        new
                        {
                            Id = 10,
                            CountryCode = "GB",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 0,
                            RatePercent = 20.0m
                        },
                        new
                        {
                            Id = 11,
                            CountryCode = "GB",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 1,
                            RatePercent = 5.0m
                        },
                        new
                        {
                            Id = 12,
                            CountryCode = "GB",
                            EffectiveFrom = new DateOnly(2015, 1, 1),
                            RateKind = 2,
                            RatePercent = 0.0m
                        });
                });

            modelBuilder.Entity("LedgerLoop.Api.Domain.Invoice", b =>
                {
                    b.HasOne("LedgerLoop.Api.Domain.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LedgerLoop.Api.Domain.InvoiceLine", b =>
                {
                    b.HasOne("LedgerLoop.Api.Domain.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("LedgerLoop.Api.Domain.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("LedgerLoop.Api.Domain.Invoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
